language: python

python:
  - '3.6'

script:
  - pip3 install -r requirements.txt
  - pytest

deploy:
  provider: pypi
  user: khozzy
  password:
    secure: U7bfuxnP8i/5roS1frPVi3EuYSw2YmNGwnGumr2Fw+GRbzYP0AyB+pTzZ9CbKk8A8gCWnsGR+ky00SdLcAAmzpoui9QxPlr1ndRy/z8W7KY5EGe2R65VoM1ztCOH3ZtclfGrQAMYHz4HLvXrGbkf5+xeYRhhW/tC4fH+VwHMNH8eT+e2+1xLkHTBQr0Devp1Qthl3EMJhIUSiCtj15wR+k9a3hN/plLTFWFuHg82OTmuh2UkKJ1z9kxLxPRC2+cB7XivPKcPW9MpEDr4jzh+T+4SpjxNbL6hzXMGUz/6FXv8IUojjN5OjsOsKzEY5B2tWSs81z+NCgS8EVggYDmtQHSL+O1jdEBLUpNRLaVYoH6fbsBVujEzNnPw1fbk5idlMUpQfxrDg/CbPL5lQ7XQ9OiS7/LRz98v1NwSwzARGNGgOx9yFBpsmPyfVA/2xzrGCLppkaftGSwPegxGe5w0ULFo/ITmaG4Sux1JBsODkWGParDlTXtcGMjWlZOhBTm+nlobeIxMtSG+M//+xOcE2KqdOkPFYZgSEDeqZoO1pglmxMso8FTGYcOWUW/wEErwP6MFAllWWwVPOPTAS++Ll3jJBhGNXyo9ZuKlXBTk/immrWoGUNHfCZXkblfvmo4D7vMg2HLyKbgAdShfLX/M8kYGzQTw8JtflhcgsuaygSU=
  on:
    tags: true
    branch: master
